### ISSUE TITLE
Random error.

### ISSUE THREAD

**Issue by BizLight** [NebulousCloud/helix#100]
Hello!
I just started helix for the first time and I got this error:

[ERROR] gamemodes/helix/plugins/mapscene.lua:21: attempt to call field 'IsEmpty' (a nil value)
  1. v - gamemodes/helix/plugins/mapscene.lua:21
   2. unknown - gamemodes/helix/gamemode/core/libs/sh_plugin.lua:481

Even though I barely got to the character menu. Is this supposed to happen or is it just me?
If so, could you please help me fix this issue? Thanks in advance.

**Comment by alexgrist** [comment]
Your GMod server needs to be updated.
