### ISSUE TITLE
Error when player joins - Unplayable

### ISSUE THREAD

**Issue by Adaster54** [NebulousCloud/helix#105]
Hi, when I try to connect my server after adding Helix and the Skeleton schema I get the following error: 
[ERROR] gamemodes/helix/plugins/mapscene.lua:21: attempt to call field 'IsEmpty' (a nil value)
  1. v - gamemodes/helix/plugins/mapscene.lua:21
   2. unknown - gamemodes/helix/gamemode/core/libs/sh_plugin.lua:481
When I click on "Create a New Character" the screen turns black and I can only open the console.
*I'd like to note that when I use the Helix version from late April I get no errors and it works fine.

**Comment by alexgrist** [comment]
Your server is not up to date with the latest version of garrysmod.
