### ISSUE TITLE
Containers dont appear in entities\helix

### ISSUE THREAD

**Issue by Adaster54** [NebulousCloud/helix#108]
The containers plugin doesn't appear for me in entities\helix.
*I made sure it's actually in the helix plugins folder.
*No error message.

**Comment by alexgrist** [comment]
You only need to spawn the regular prop version and it will become a container.

**Comment by Taxin2012** [comment]
You have file, that named "definations", just find model path and spawn this prop by spawn list

**Comment by Adaster54** [comment]
Thanks for the help!
