### ISSUE TITLE
lua error with animation

### ISSUE THREAD

**Issue by KHishGit** [NebulousCloud/helix#109]
I keep getting this error whenever I fire, aim, or reload any weapon, hl2, FA:S2, or even the fists that come with Helix. This problem also causes models to t pose and glitch out , even default basic models. any help would be much appreciated as i have tried clearing the database, clearing all addons, using fresh, untouched installations of helix and the skeleton on a fresh server and still get the error. Thanks!
[ERROR] gamemodes/helix/gamemode/core/hooks/sh_hooks.lua:196: attempt to index local 'animation' (a nil value)
1. unknown - gamemodes/helix/gamemode/core/hooks/sh_hooks.lua:196
2. SetAnimation - [C]:-1
3. unknown - gamemodes/helix/entities/weapons/ix_hands.lua:366

**Comment by KHishGit** [comment]
OK so update found out it is one of my addons, doing a painful trial and error test to see which one it is to let you all know for future reference

**Comment by alexgrist** [comment]
Are you using the GMod Legs plugin by any chance?

**Comment by KHishGit** [comment]
yes gonna test that now lol
guessing its not compatible

**Comment by alexgrist** [comment]
Yeah. Use our legs plugin instead, it’s mostly the same code but compatible with Helix.

**Comment by KHishGit** [comment]
yup that was it where can i get that

**Comment by alexgrist** [comment]
Just put this file into your Schema plugins: https://github.com/NebulousCloud/helix-plugins/blob/master/legs.lua

**Comment by KHishGit** [comment]
that fixed it thank you!
