### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by ExtReMLapin** [NebulousCloud/helix#122]
[ERROR] gamemodes/helix/plugins/wepselect.lua:73: Tried to use a NULL entity!
  1. GetPrintName - [C]:-1
   2. v - gamemodes/helix/plugins/wepselect.lua:73
    3. unknown - gamemodes/helix/gamemode/core/libs/sh_plugin.lua:481

**Comment by ExtReMLapin** [comment]
Bodies should not disappear when player respawn

**Comment by ExtReMLapin** [comment]
Editing a vendor name update it on the right panel but not on the left panel (wtf???)

**Comment by ExtReMLapin** [comment]
~~Improve~~ Add stamina/damage visual effect

**Comment by ExtReMLapin** [comment]
Add noises when someone opens a container

**Comment by alexgrist** [comment]
Please create issues or suggestions, not todo lists.

**Comment by ExtReMLapin** [comment]
you literally told me to post here lol

**Comment by alexgrist** [comment]
Yeah, create issues or suggestions
