### ISSUE TITLE
[Next gmod update] Player.SelectWeapon(entity) instead of Player.SelectWeapon(entity_class))

### ISSUE THREAD

**Issue by ExtReMLapin** [NebulousCloud/helix#136]
https://gmod.facepunch.com/commits/1

>Player.SelectWeapon() can now accept Weapon entities directly

It's going to be available in the next update, probably a micro-optimization but still

(See it as a TODO)

**Comment by ExtReMLapin** [comment]
Since it's related I should probably not open another issue : 

>Player.GetWeapons() ensures the output table is sequential and now starts with 1 instead of 0.


Things to change : 

https://github.com/NebulousCloud/helix/blob/master/plugins/wepselect.lua#L147

And move other calls from pairs to ipairs

**Comment by alexgrist** [comment]
The `GetWeapons` usage for the weapon selector is just to make the table sequential.
