### ISSUE TITLE
Lua errors upon client connecting.

### ISSUE THREAD

**Issue by sanny-io** [NebulousCloud/helix#138]
Clientside lua errors upon connecting to the server using both the sample schema and HL2 RP on ix bdf40f3. Fresh install of both the dedicated server and gmod game client.

> 
> [sanny|2|STEAM_0:0:13347490] Lua Error:
> 
> [ERROR] gamemodes/helix/gamemode/core/derma/cl_character.lua:496: attempt to perform arithmetic on field 'currentAlpha' (a nil value)
>   1. unknown - gamemodes/helix/gamemode/core/derma/cl_character.lua:496
> 
> 
> [sanny|2|STEAM_0:0:13347490] Lua Error:
> 
> [ERROR] gamemodes/helix/gamemode/core/libs/thirdparty/sh_tween.lua:269: bad argument #1 to 'insert' (table expected, got string)
>   1. insert - [C]:-1
>    2. checkSubjectAndTargetRecursively - gamemodes/helix/gamemode/core/libs/thirdparty/sh_tween.lua:269
>     3. checkNewParams - gamemodes/helix/gamemode/core/libs/thirdparty/sh_tween.lua:284
>      4. new - gamemodes/helix/gamemode/core/libs/thirdparty/sh_tween.lua:365
>       5. CreateAnimation - gamemodes/helix/gamemode/core/libs/sh_animation.lua:84
>        6. SetAlpha - gamemodes/helix/plugins/chatbox/derma/cl_chatbox.lua:891
>         7. SetActive - gamemodes/helix/plugins/chatbox/derma/cl_chatbox.lua:927
>          8. Init - gamemodes/helix/plugins/chatbox/derma/cl_chatbox.lua:869
>           9. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:37
>            10. CreateChat - gamemodes/helix/plugins/chatbox/sh_plugin.lua:54
>             11. v - gamemodes/helix/plugins/chatbox/sh_plugin.lua:87
>              12. unknown - gamemodes/helix/gamemode/core/libs[sanny|2|STEAM_0:0:13347490] Lua Error:
> 
> [ERROR] gamemodes/helix/gamemode/core/derma/cl_character.lua:496: attempt to perform arithmetic on field 'currentAlpha' (a nil value)
>   1. unknown - gamemodes/helix/gamemode/core/derma/cl_character.lua:496
> 
> 
> [sanny|2|STEAM_0:0:13347490] Lua Error:
> 
> [ERROR] gamemodes/helix/gamemode/core/derma/cl_character.lua:496: attempt to perform arithmetic on field 'currentAlpha' (a nil value)
>   1. unknown - gamemodes/helix/gamemode/core/derma/cl_character.lua:496
> 
> 
> [sanny|2|STEAM_0:0:13347490] Lua Error:
> 
> [ERROR] gamemodes/helix/gamemode/core/libs/thirdparty/sh_tween.lua:269: bad argument #1 to 'insert' (table expected, got string)
>   1. insert - [C]:-1
>    2. checkSubjectAndTargetRecursively - gamemodes/helix/gamemode/core/libs/thirdparty/sh_tween.lua:269
>     3. checkNewParams - gamemodes/helix/gamemode/core/libs/thirdparty/sh_tween.lua:284
>      4. new - gamemodes/helix/gamemode/core/libs/thirdparty/sh_tween.lua:365
>       5. CreateAnimation - gamemodes/helix/gamemode/core/libs/sh_animation.lua:84
>        6. OnSetActive - gamemodes/helix/gamemode/core/derma/cl_charload.lua:261
>         7. SetActiveSubpanel - gamemodes/helix/gamemode/core/derma/cl_subpanel.lua:210
>          8. Init - gamemodes/helix/gamemode/core/derma/cl_charload.lua:391
>           9. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:37
>            10. Add - lua/includes/extensions/client/panel.lua:461
>             11. Init - gamemodes/helix/gamemode/core/derma/cl_character.lua:338
>              12. Create - lua/includes/extensions/cli[LOG] sanny (STEAM_0:0:13347490) has disconnected.
> Dropped sanny from server (Disconnect by user.)

**Comment by alexgrist** [comment]
Reverted bdf40f3

**Comment by sanny-io** [comment]
👍 That did it.

The gamemode looks super clean now by the way, love your guys' work.

**Comment by ExtReMLapin** [comment]
rude
