### ISSUE TITLE
ix.util.FindPlayer redesign ?

### ISSUE THREAD

**Issue by ExtReMLapin** [NebulousCloud/helix#140]
I'm opening an issue instead of directly making a pull request because I'm not sure the whole thing will be accepted.

Here is how `ix.util.FindPlayer` (for playernames only) works currently : 

It finds the first playername that matches.
But not the BEST match.

Let me explain : 

Let's say you have the players : 

 

```
[1] = "Bob Good"
[2] = "Roger Oakleen"
[3] = "Leenda Breezehome"
```

`ix.util.FindPlayer("leen")`

will return the `"Roger Oakleen"` player instead of `"Leenda Breezhome"`

This is why a system working with match percentage should be done.

Here the example is a bit exotic but with multiple guys called "John" or "Johnson" on your server, it's going to be a mess to find the right one without updating the search function. 

(I'm thinking about the PM command)

**Comment by ZeMysticalTaco** [comment]
Could have it autofill in chat in ghosted letters the name it's detecting, keep typing until the name changes

**Comment by ExtReMLapin** [comment]
Or maybe a list over the chatbox and pressing tab navigates in the list
