### ISSUE TITLE
pac3 parts not drawing on ragdolled players

### ISSUE THREAD

**Issue by notanennx** [NebulousCloud/helix#155]
Pac3 parts from pacoutfit item base not drawn on ragdolled players, but work fine on players.

You can reproduce it by:
1) Wear a default sh_skullmask outfit
2) Spawn a camera with toolgun and appear on camera
3) Ragdoll yourself but /charfallover 4
4) Watch your pac parts disappear when you get ragdolled and appear again when you get back up

**Comment by DefenderVex** [comment]
I don't think PAC parts have ever persisted on any server I've been on when someone ragdolls.

**Comment by alexgrist** [comment]
This doesn't seem to be an issue on my dev server, using a PAC hat definitely appears on the ragdolled player.

**Comment by notanennx** [comment]
Ok, thanks, it seems I had an old PAC3 version
