### ISSUE TITLE
Error about menu

### ISSUE THREAD

**Issue by tori162** [NebulousCloud/helix#158]
![20191123_120528](https://user-images.githubusercontent.com/58290963/69793242-62d09b00-120b-11ea-87fa-d485ae71e4fe.jpg)

![20191110_231221](https://user-images.githubusercontent.com/58290963/69793259-69f7a900-120b-11ea-84f6-201e41c088d7.jpg)

Not move in menu

**Comment by impulsh** [comment]
Make sure there are no errors when you start up your server and connect to it

**Comment by tori162** [comment]
Like what?

**Comment by Selenter1** [comment]
Remove all addons modifying Derma Skin on their server. Here is an example of one of these add-ons:
https://steamcommunity.com/sharedfiles/filedetails/?id=682717037

**Comment by tori162** [comment]
But I have no that addon
