### ISSUE TITLE
What is this error?

### ISSUE THREAD

**Issue by MusiC001** [NebulousCloud/helix#160]
[ERROR] gamemodes/helix/gamemode/core/libs/sh_item.lua:20: attempt to index local 'zeroInv' (a nil value)
  1. unknown - gamemodes/helix/gamemode/core/libs/sh_item.lua:20
   2. Include - [C]:-1
    3. IncludeDir - gamemodes/helix/gamemode/core/sh_util.lua:85
     4. unknown - gamemodes/helix/gamemode/shared.lua:94
      5. include - [C]:-1
       6. unknown - gamemodes/helix/gamemode/init.lua:19
        7. DeriveGamemode - [C]:-1
         8. unknown - gamemodes/ixhl2rp/gamemode/init.lua:3

EDIT: AND

[ERROR] gamemodes/helix/gamemode/core/hooks/sh_hooks.lua:534: attempt to index local 'curInv' (a nil value)
  1. Run - gamemodes/helix/gamemode/core/hooks/sh_hooks.lua:534
   2. Add - gamemodes/helix/gamemode/core/meta/sh_inventory.lua:568
    3. Transfer - gamemodes/helix/gamemode/core/meta/sh_item.lua:479
     4. v - gamemodes/ixhl2rp/plugins/persistent_corpses.lua:176
      5. Run - gamemodes/helix/gamemode/core/libs/sh_plugin.lua:481
       6. v - gamemodes/ixhl2rp/plugins/persistent_corpses.lua:154
        7. unknown - gamemodes/helix/gamemode/core/libs/sh_plugin.lua:481

EDIT2: I get it, what is this error about, but i dont know how fix it.

**Comment by MusiC001** [comment]
And now i get new problem. I cant drop items with this error:
[ERROR] gamemodes/helix/gamemode/core/meta/sh_item.lua:518: attempt to index local 'inventory' (a nil value)
  1. Transfer - gamemodes/helix/gamemode/core/meta/sh_item.lua:518
   2. OnRun - gamemodes/helix/gamemode/core/libs/sh_item.lua:189
    3. PerformInventoryAction - gamemodes/helix/gamemode/core/libs/sh_item.lua:821
     4. func - gamemodes/helix/gamemode/core/libs/sh_item.lua:957
      5. unknown - lua/includes/extensions/net.lua:32

**Comment by MusiC001** [comment]
I fix problems, but i have another.
Clothes dont work.

**Comment by MusiC001** [comment]
I use
ITEM.bodyGroup={
     [torso] = 1
}
But when i put on one thing and another, will put on the last, but both equipped.

**Comment by alexgrist** [comment]
You will need to look for errors in your server console, likely from your schema. We primarily have support provided via our Discord server.
