### ISSUE TITLE
Not a Valid Font Error

### ISSUE THREAD

**Issue by jellyton69** [NebulousCloud/helix#164]
On a fresh copy of Helix, using the skeleton schema. Whenever the weapon wheel is activated, this error is received, both on server and client.

```
[ERROR] gamemodes/helix/plugins/wepselect.lua:72: 'ixWeaponSelectFont' isn't a valid font

  1. SetFont - [C]:-1
   2. v - gamemodes/helix/plugins/wepselect.lua:72
    3. unknown - gamemodes/helix/gamemode/core/libs/sh_plugin.lua:481

```

**Comment by Aspect12** [comment]
Thank you for the help impulse, very cool!

**Comment by impulsh** [comment]
@Aspect12 The user has resolved the issue on their end and communicated this via discord

Thank you for your concern
