### ISSUE TITLE
After picking up an item, the description disappears

### ISSUE THREAD

**Issue by SleepyMode** [NebulousCloud/helix#17]
I dropped an item that had a proper description, dropped it(You can see that it still has a description when I look at it), but then when I pick it back up - the description disappears.

https://www.youtube.com/watch?v=1jRSvB7SszM

**Comment by impulsh** [comment]
How are you setting the description - text in `ITEM.description` or using `ITEM:GetDescription()`?

**Comment by impulsh** [comment]
After some testing, it appears that this happens after an autorefresh
