### ISSUE TITLE
Character creation hook

### ISSUE THREAD

**Issue by geferon** [NebulousCloud/helix#175]
I have noticed that on the serverside code for creating a character, the server makes no check other than if the user has reached it max characters amount, as seen here:
https://github.com/NebulousCloud/helix/blob/master/gamemode/core/libs/sh_character.lua#L896-L972
(excepting the character vars OnValidate)

Currently, the only way for plugins or anything really, to restrict a player from creating a character, is to create a character var that has a OnValidate function.

It would be nice if we could also have a kind of check like the one made on the character choosing https://github.com/NebulousCloud/helix/blob/master/gamemode/core/libs/sh_character.lua#L861

**Comment by alexgrist** [comment]
Every character var that has an `OnValidate` is checked on creation which includes a check that the client has the whitelist for the faction they're attempting to make a character for.

**Comment by geferon** [comment]
> Every character var that has an `OnValidate` is checked on creation which includes a check that the client has the whitelist for the faction they're attempting to make a character for.

Yeah, you're right, I was looking at the code of character creating and saw no checks of whitelist anywhere, thought it didn't do any, I didn't realize the OnValidate had a whitelist check on the faction var.
I made this issue as I was looking into the character creation code trying to see if there was maybe a hook to do custom checks upon creation that didn't depend on having a character var, and didn't see any check for the whitelist, therefore making me think there was a problem, guess I was wrong.
Anyways, I've rewritten the issue as of my original request, or what I was originally aiming for rather.

**Comment by impulsh** [comment]
[OnCharacterCreated](https://docs.gethelix.co/hooks/Plugin.html#OnCharacterCreated) already exists

**Comment by impulsh** [comment]
Oh, you mean before character creation. Generally you should rely on `ix.char.RegisterVar` for checking validity. What's your use case?

**Comment by geferon** [comment]
Limit characters per faction globally and/or per user (unlike the only limit of maximum characters, regardless of any conditions), ban users from creating characters, and not allow character creation when certain conditions are met, as with above only some groups of users being able to go over that limit. Mainly the first three would be my use case, but I can see it being used more as well.
