### ISSUE TITLE
Containers Money Autoreload issue

### ISSUE THREAD

**Issue by geferon** [NebulousCloud/helix#179]
Currently in servers with Autoreload enabled, as a file gets modified and a reload gets triggered, every single container will have it's internal "money" variable set to 0, loosing all of the money stored on them.

It seems that somehow, even tho the definition of the entities money variable is on the entity base (as seen here: https://github.com/NebulousCloud/helix/blob/master/plugins/containers/entities/entities/ix_container.lua#L15 ) it somehow gets set on every single ix_container entity upon auto-reload when modifying a file.

I've tested locally, and moving the `ENT.money = 0` inside the Initialize as `self.money = 0` seems to do the trick.

**Comment by Taxin2012** [comment]
https://github.com/NebulousCloud/helix/pull/80

**Comment by geferon** [comment]
> #80

Ah, upon creating the issue I didn't see that issue, tho I dunno if they'd be willing to admit a fix, as I found out how to solve the issue as stated above.

**Comment by alexgrist** [comment]
You should not have autorefresh enabled on a production server as this will most definitely lead to bigger issues that aren't releated to Helix as it's only intended for development purpose (and barely works at that). 

I'll push a fix for this shortly.
