### ISSUE TITLE
Clockwork migration / Model class Issue

### ISSUE THREAD

**Issue by Contamination** [NebulousCloud/helix#180]
HEllo everyone, i decided to move to HElix for my gamemode and i'm starting from zero with the HL2RP schema.

I encountered several problems, here they are:

- I use Ragdolls for the playermodels, i do registered them in the sh_anims but it didn't seems to work...

- I intent to create classes with weapons on spawn, not in the inventory but in the weapon wheel, I don't understand Lua very much, I was using this in Sv_hooks of the CW schema back then:

> if (player:GetCharacterData("customclass") == "Soldat") then
> Clockwork.player:GiveSpawnWeapon(player,"tiramisu_m_mk2_carbine" )
> end

If you guys could help me, i'll be glad! :D
Thanks!

**Comment by garytate** [comment]
Best place for support is in the Discord server: https://discord.gg/2AutUcF

**Comment by ExtReMLapin** [comment]
you mispelled cockwork
