### ISSUE TITLE
Creating Data for characters and items

### ISSUE THREAD

**Issue by fireshadows10** [NebulousCloud/helix#193]
Hello, and sorry for the disturbance but I've been trying to figure out how to create data for characters and items for two days now without success. The documentation website is also not very helpful in this matter. I tried the following code but it does nothing apparently:
ix.char.RegisterVar("points", {
	field = "points",
	fieldType = ix.type.number,
	default = 200,
	isLocal = true,
})
I also have a script to read and change that data, however it gives me an error:

local checkbank = LocalPlayer():GetCharacter():GetData("points", 200)
LocalPlayer():GetCharacter():SetData("bankmoney", checkbank + 100)
The error is:
cl_init.lua:93: attempt to call method 'SetData' (a nil value)
  Can someone please help me or clarify to me how to make data? I am also interested for item data. Much appreciated :)

**Comment by wowmod** [comment]
You can't SetData on client- join discord for better support. This is not an issue.
https://discord.gg/2AutUcF
