### ISSUE TITLE
No check(s) to prevent characters from selling an item at Max Stock to Vendors

### ISSUE THREAD

**Issue by WolffeUS** [NebulousCloud/helix#206]
As far as I can tell, there are no check(s) preventing a player from selling items, with stock, that are already at their defined capacity, thus allowing for overflow.

**Comment by alexgrist** [comment]
You are correct, although I'm unsure if fixing it might cause issues for others. It may be expected behaviour to be able to sell to the vendor despite being max stock whereas others may expect it to disallow it.
