### ISSUE TITLE
Buying from vendors does nothing

### ISSUE THREAD

**Issue by SleepyMode** [NebulousCloud/helix#24]
When you buy from the vendors, nothing happens, press the purchase and just.. nothing.

**Comment by impulsh** [comment]
There are no errors or other info that appear?

**Comment by alexgrist** [comment]
Does it work after removing and recreating the vendor? It may have been persisted by accident.

**Comment by SleepyMode** [comment]
I ended up getting this error just now: [ERROR] gamemodes/helix/gamemode/core/libs/sh_log.lua:40: attempt to index local 'info' (a nil value)

  1. Parse - gamemodes/helix/gamemode/core/libs/sh_log.lua:40

   2. Add - gamemodes/helix/gamemode/core/libs/sh_log.lua:64

    3. TakeMoney - gamemodes/helix/gamemode/core/libs/sh_currency.lua:83

     4. unknown - gamemodes/helix/plugins/vendor/sh_plugin.lua:324

      5. func - gamemodes/helix/gamemode/core/libs/thirdparty/sh_netstream2.lua:117

       6. unknown - lua/includes/extensions/net.lua:32

**Comment by SleepyMode** [comment]
I added the following line to the bottom of sh_log.lua:
```ix.log.AddType("money", "The money of %s has changed by %d.")```

And it worked, vendors now work, but I'm not sure where to put it in the pull request, and it's still bugged in the vanilla schema.

**Comment by alexgrist** [comment]
Ah, it's something we had in our schema and didn't notice there wasn't a check for a callback before it attempted to log. Wasn't sure if people would want the (likely) spammy log of money changes in the framework.
