### ISSUE TITLE
DMenu error after Garry's Mod november update

### ISSUE THREAD

**Issue by OffLegAz** [NebulousCloud/helix#243]
After GMod commit named [**'Improvements to DMenu while parented to modal panel'**](https://github.com/Facepunch/garrysmod/commit/6090f6707771cacab8554a576823cb3462dd00a3) on open all derma menus show error like one given below:
```
[ERROR] lua/vgui/dmenu.lua:223: attempt to call method 'IsModal' (a nil value)
  1. ixOpen - lua/vgui/dmenu.lua:223
   2. Open - gamemodes/helix/gamemode/core/derma/cl_overrides.lua:130
    3. func - gamemodes/helix/plugins/recognition.lua:126
     4. unknown - lua/includes/extensions/net.lua:32
```

**Comment by alexgrist** [comment]
As far as I'm aware there hasn't been an update pushed to main, we don't develop based on the development branch due to how often changes are pushed and reverted.

**Comment by OffLegAz** [comment]
Fair enough.
