### ISSUE TITLE
I would like help

### ISSUE THREAD

**Issue by SmarterJoker** [NebulousCloud/helix#271]
How does one make a specific class or role only allowed to one person? Is it done by steamid?

**Comment by NforceSSP** [comment]
It can be done by STEAMID, yes.
For development questions, ask them here instead: https://discord.gg/aepdfFxqkG

**Comment by SmarterJoker** [comment]
Ok I joined,  I am Joker, but it says I do not have the permission to send messages.

**Comment by impulsh** [comment]
https://docs.gethelix.co/hooks/class/#CanSwitchTo

> Ok I joined, I am Joker, but it says I do not have the permission to send messages.
Read the info channel to gain access
