### ISSUE TITLE
Black Screen after creating character

### ISSUE THREAD

**Issue by OddInc** [NebulousCloud/helix#44]
Receiving error:

[ERROR] gamemodes/helix/gamemode/core/hooks/sv_hooks.lua:307: bad argument #2 to 'Create' (number expected, got nil)

Create - [C]:-1
Run - gamemodes/helix/gamemode/core/hooks/sv_hooks.lua:307
3. Setup - gamemodes/helix/gamemode/core/meta/sh_character.lua:142
4. func - gamemodes/helix/gamemode/core/libs/sh_character.lua:734
5. unknown - lua/includes/extensions/net.lua:32

Trying to reload gives you an infinite loading screen with the error:

[ERROR] SQL Callback Error!
gamemodes/helix/gamemode/core/libs/thirdparty/sv_mysql.lua:571: [mysql] SQL Callback Error!
gamemodes/helix/gamemode/core/libs/thirdparty/sv_mysql.lua:571: [mysql] SQL Callback Error!
gamemodes/helix/gamemode/core/libs/thirdparty/sv_mysql.lua:565: [mysql] SQL Query Error!
Query: SELECT `item_id`, `inventory_id`, `unique_id`, `data`, `character_id`, `player_id`, `x`, `y` FROM `ix_items`  WHERE `inventory_id` IN (4)
no such column: character_id

  1. error - [C]:-1
   2. Execute - gamemodes/helix/gamemode/core/libs/thirdparty/sv_mysql.lua:571
    3. LoadData - gamemodes/helix/gamemode/core/libs/sv_player.lua:47
     4. unknown - gamemodes/helix/gamemode/core/hooks/sv_hooks.lua:36

Notes:
This helix framework was JUST downloaded from right here. 
The schema is the skeleton schema.

The "helix-master" folder was renamed to "helix"

**Comment by alexgrist** [comment]
The error shows that the database doesn’t have the character_id column, were you using Helix before the beta release? If so, you will need to drop your SQL tables (this will delete all character, player and item data!!).

Helix Beta is not compatible with the previous versions.

**Comment by alexgrist** [comment]
If this is just a development environment and you don’t care about the data, since you’re using SQLite you can just delete garrysmod/sv.db and garrysmod/data/helix

**Comment by OddInc** [comment]
Deleting both the database and helix data folder worked. Thank you so much!

Was not aware of the data/helix folder. Just deleting the sv.db did not work but deleting both and reloading fixed the problem. Thank you!
