### ISSUE TITLE
Vendors are rapidly duplicating

### ISSUE THREAD

**Issue by OddInc** [NebulousCloud/helix#52]
Cause is unknown. Looked in one direction, suddenly frames went down to 10. Started pulling out vendors, were a lot.

**Comment by alexgrist** [comment]
This is a known issue due to a late change to fix LoadData being called too early, every lua refresh will call LoadData which causes duplication if you’re spawning entities there. Will look into a workaround.

**Comment by OddInc** [comment]
Thank you. Sorry for all the issue reports. Not tying to be annoying.

**Comment by alexgrist** [comment]
It’s fine. We’d rather know the issues people are experiencing than not, for now though delete the data files for vendors or delete the vendors before a refresh, not ideal but works for now.
