### ISSUE TITLE
Rolls do not print in the console

### ISSUE THREAD

**Issue by ghost** [NebulousCloud/helix#67]
Would it be possible for the result of rolls to print in the console/logs?

All what appears now is simply /roll.

**Comment by ElectricSunset** [comment]
I've noticed that the actual outcome of the roll isn't stored anywhere and instead is sent only in chat (gamemode/core/sh_commands.lua):
```
ix.chat.Send(client, "roll", tostring(math.random(0, maximum)), nil, nil, {
			max = maximum
		})
```
Maybe if we assign:
`rolled_outcome = tostring(math.random(0, maximum))`
Then putting that in:
```
ix.chat.Send(client, "roll", rolled_outcome, nil, nil, {
			max = maximum
		})
```
I still have no idea how I would return the value of `rolled_outcome` in an `ix.log.AddType` in plugins/logging.lua
