### ISSUE TITLE
Items disappear when dropped

### ISSUE THREAD

**Issue by OddInc** [NebulousCloud/helix#76]
When an item is dropped, it doesn't even drop. It just poofs our of existence. All items have world models and sometimes work but 9/10 times, they disappear.

**Comment by alexgrist** [comment]
Check your server for errors, we have a live server running the current github version (updated daily) and not experiencing this issue.

**Comment by WizzyDev** [comment]
To pitch in- Have you changed anything to do with items, is it default items?

**Comment by OddInc** [comment]
[ERROR] gamemodes/helix/gamemode/core/meta/sh_item.lua:447: attempt to index local 'inventory' (a nil value)
  1. Transfer - gamemodes/helix/gamemode/core/meta/sh_item.lua:447
   2. OnRun - gamemodes/helix/gamemode/core/libs/sh_item.lua:177
    3. PerformInventoryAction - gamemodes/helix/gamemode/core/libs/sh_item.lua:807
     4. func - gamemodes/helix/gamemode/core/libs/sh_item.lua:943
      5. unknown - lua/includes/extensions/net.lua:32

**Comment by OddInc** [comment]
This error occurs whenever I drop a weapon or item.

Is it ALL items.
I have not touched any sh_item files.

**Comment by alexgrist** [comment]
Have you edited the framework files at all?

**Comment by OddInc** [comment]
Only sh_currency to change the name

**Comment by alexgrist** [comment]
But you don't need to edit the framework to do that, we edit the name in hl2rp https://github.com/NebulousCloud/helix-hl2rp/blob/master/schema/sh_configs.lua#L3

**Comment by OddInc** [comment]
Was working fine, but upon server restart, I cannot pick up items

**Comment by alexgrist** [comment]
Can you upload your console.log?

**Comment by OddInc** [comment]
[console.log](https://github.com/NebulousCloud/helix/files/2730038/console.log)

**Comment by OddInc** [comment]
I don't think there's any errors in there that are visible.

**Comment by alexgrist** [comment]
You have a lot of addons and there are a few errors but it's possible an addon is conflicting.

**Comment by OddInc** [comment]
Could it be possible a lot of props on a map could be causing it? Using the same exact addons  and schema in single player allows the items to be picked up.

**Comment by alexgrist** [comment]
Shouldn't do, we have a lot of props on our server without that issue. We run the current live version of Helix so it would've likely happened if it were something in the framework.

**Comment by OddInc** [comment]
Do you have any form of netstream on your server?

**Comment by OddInc** [comment]
What hook does helix use for picking up items that could be over written?

**Comment by OddInc** [comment]
Asking so I can decompile all the addons and search to see.

**Comment by OddInc** [comment]
Is there a certain string or any text I should be looking for?

**Comment by alexgrist** [comment]
It's likely something for entities being spawned, so it could be anything

**Comment by OddInc** [comment]
Can't seem to figure out what is causing it, meanwhile in SP everything is fine :/

**Comment by OddInc** [comment]
It appears to be the map itself. Switching to a different map allows me to pick up items, while the default map does not.

It is definitely the map.

**Comment by OddInc** [comment]
It's one of those maps where it's layered, as in if you are on one map, if you noclip and fly down, there's another map, so is it possible that the item is thinking it's not on the ground?

**Comment by alexgrist** [comment]
It's possible, not had the issue myself but it could be falling through the floor otherwise.

**Comment by OddInc** [comment]
Picking up said item doesn't work on the map at all in MP, but works fine in SP. Not really sure what is going on.

**Comment by alexgrist** [comment]
Did you try without any workshop addons on the server temporarily?

**Comment by OddInc** [comment]
Even with nothing on the server (except the map), the problem persists.

Made a completely different collection with just the map.
Deleted the workshop.lua
Still can pick up items on gm_flatgrass
This was tested with a HL2 chair as the prop, so it's not the prop I'm using either.

**Comment by OddInc** [comment]
Just tried with a fresh install of helix, just in case.
Problem is still there.

**Comment by OddInc** [comment]
It should also be noted that when this issue is in effect, items cannot be picked up with the IX hands either

**Comment by OddInc** [comment]
I believe this problem was due to a very specific map problem. This is more or less invalid.
