### ISSUE TITLE
ix.config.SetDefault doesn't function in schema

### ISSUE THREAD

**Issue by homonovus** [NebulousCloud/helix#77]
Calling ix.config.SetDefault in a schema's sh_configs.lua doesn't seem to properly set the config's default value.

**Comment by OddInc** [comment]
make sure that in your sh_schema file you include:
`ix.util.Include("sh_configs.lua")`

also make sure it is in the "schema" folder of your schema

**Comment by SleepyMode** [comment]
Can't seem to reproduce.
Are you sure you're including your `sh_configs.lua` file correctly?

From the `sh_schema.lua` file, do it this way:
```lua
ix.util.Include("sh_configs.lua")
```
