### ISSUE TITLE
Vendor token amount is glitchy

### ISSUE THREAD

**Issue by ElectricSunset** [NebulousCloud/helix#84]
Trying to add large token amounts to vendors causes the value to either be rejected or reduce to a random number like 58368.

**Comment by alexgrist** [comment]
Likely due to https://github.com/NebulousCloud/helix/blob/master/plugins/vendor/sh_plugin.lua#L577

**Comment by ElectricSunset** [comment]
Yes, that definitely looks like the cause of what I was seeing, increasing the accepted number of bits to 32 should solve that problem for me. Thanks for the helpful response on this issue.

**Comment by alexgrist** [comment]
I'm not really opposed to upping the bits in the framework anyway, it's mainly just low for micro-optimization purposes.
