### ISSUE TITLE
Player don't lose Items on Death ?

### ISSUE THREAD

**Issue by Teskocf** [NebulousCloud/helix#87]
Hey i have the Problem that the Player's keep their items after Dying

**Comment by alexgrist** [comment]
If you wish to remove all items from a character on death, you will need to create this feature. The framework by default does not drop or remove items from a character after dying.

**Comment by Teskocf** [comment]
Thanks for the anwser :)
in which file is the part where the player dies ?

**Comment by alexgrist** [comment]
You would not modify the framework to do this, in your schema you'd need to add the weapon dropping code to something like `DoPlayerDeath`

**Comment by Teskocf** [comment]
Ok Thanks ^^

**Comment by Teskocf** [comment]
Again one question if i have this how do i select all items from the dead player and let them delete ?
is there a ix.removeallitems() or something ?

**Comment by SleepyMode** [comment]
Iterate over the inventory.

**Comment by Teskocf** [comment]
Ok i found a Plugin that this does problem is that the items dont be transfered form the inventory in the new inventory to loot the bodie

and this is the Plugin
https://github.com/NebulousCloud/helix-plugins/blob/master/persistent_corpses.lua

This is the Code
`		-- create new inventory
		local inventory = ix.item.CreateInv(width, height, os.time())
		inventory.noSave = true

		if (ix.config.Get("dropItemsOnDeath")) then
			for _, slot in pairs(charInventory.slots) do
				for _, item in pairs(slot) do
					if (item.dropOnDeath) then
						item:Transfer(inventory:GetID(), item.gridX, item.gridY)
					end
				end
			end
		end`

**Comment by alexgrist** [comment]
Are you using the item.dropOnDeath on each item you want to drop, the code has a condition for that to be true on the item for it to drop.

**Comment by alexgrist** [comment]
Please use the #support channel on Discord as this is not a Helix bug.
