### ISSUE TITLE
Intro Issues

### ISSUE THREAD

**Issue by SANSOdev** [NebulousCloud/helix#89]
Just wanted to post this here so you guys can see it. Wanted to report this small issue. When you add addons to the server such as ServerGuard, etc. you get a nice little ear rape. I've repeated this problem and this time got console logs. 

`[ERROR] gamemodes/helix/gamemode/core/libs/sh_option.lua:183: expected valid option key
1. assert - [C]:-1
2. Set - gamemodes/helix/gamemode/core/libs/sh_option.lua:183
3. BeginIntro - gamemodes/helix/gamemode/core/derma/cl_intro.lua:67
4. unknown - gamemodes/helix/gamemode/core/derma/cl_intro.lua:45`

**Comment by SleepyMode** [comment]
Hello!
Ran into similar issues with SG.

It happens when SG fails to connect to the database, at least it was the issue for me.
Look for previous errors.

**Comment by SANSOdev** [comment]
Will do. Although it's odd because it's doing it for other addons too like Gbans, etc.

**Comment by impulsh** [comment]
This usually happens when something errors and causes the framework to not load properly - you should be able to find another error before the one that's spewed by the framework to find the culprit
