### ISSUE TITLE
Chatbox wrapping doesn't work correctly

### ISSUE THREAD

**Issue by ZeMysticalTaco** [NebulousCloud/helix#9]
This is the chat (slightly modified with a different font), on scrW * 0.5
![one](https://i.imgur.com/X4Zxf7V.png)

This is the same chat, but scrW * 0.4

![two](https://i.imgur.com/ETnGZ5c.png)

**Comment by impulsh** [comment]
I can't seem to reproduce this issue with changing the font or chatbox size. Is there anything else that you may have changed that could cause this?

**Comment by ZeMysticalTaco** [comment]
the only other thing I have installed that could possibly affect the chat is serverguard. I've tried uninstalling that too. didn't work.

**Comment by ZeMysticalTaco** [comment]
@impulsh I've figured out that this **only** happens the radio chat used above. I have no idea how to fix it, I'm using OnChatAdd and overriding some stuff manually through it, could that be the cause?

**Comment by impulsh** [comment]
I'd imagine that would be the likely culprit, but I wouldn't know unless you were to send me the code you're using for that chat class. It shouldn't be possible to break the text wrapping that easily either way.

**Comment by ZeMysticalTaco** [comment]
https://gist.github.com/ZeMysticalTaco/5604edff9f093c3c25a33164f4f6a65a
